avi_pool_objs:
  - name: app4-pool
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    servers:
      - ip:
           addr: '10.90.64.16'
           type: 'V4'

avi_virtualservice_objs:
  - name: app4
    services:
      - port: 80
    pool_ref: '/api/pool?name=app4-pool'
    vip:
      - ip_address:
          addr: 10.90.64.244
          type: 'V4'
        vip_id: '1'

avi_vsdatascriptset_objs:
  - name: app-4-ds
    datascript:
      - evt: VS_DATASCRIPT_EVT_HTTP_REQ
        script: "{{ request_script }}"
      - evt: VS_DATASCRIPT_EVT_HTTP_RESP
        script: "avi.vs.log(\"resp\")"
    pool_refs:
      - '/api/pool?name=app4-pool'
