# This is example of using vault for storing controller credentials"
---
- hosts: localhost
  connection: local
  vars_files:
    - "creds.yml"
  vars:
    tenant: admin
  roles:
    - role: avinetworks.avisdk
  tasks:
    - name: Print Hello
      debug: msg="Hello"

    - name: Print Controller
      debug: msg="{{username}}@{{ controller }} tenant {{tenant}}"
