# These settings are for demo purpose only. Pl. modify it as per target
# environment

avi_credentials:
  controller: "{{avi_controller}}"
  username: admin
  password: "{{avi_password}}"
  api_version: 18.2.6

# all apps use the same backend servers

app1_vip: 100.64.72.200
app2_vip: 100.64.72.201
app3_vip: 100.64.72.202
app4_vip: 100.64.72.203
complex_app_vip: 100.64.72.204
app_test_tenant_vip: 100.64.72.205
      
      
pool_server1: 100.64.72.10
pool_server2: 100.64.73.10

vcenter_password: "{{vcenter_password}}"
vcenter_url: "{{vcenter_url}}"

